import connectToDB from "./db.js";
import { TimeEntry } from "./model.js";

const db = await connectToDB(
  process.env.DATABASE_URL || "postgresql:///clg-db",
);

const now = new Date();
const ms = (d, h, m) =>
  new Date(now - d * 24 * 60 * 60 * 1000 - h * 60 * 60 * 1000 - m * 60 * 1000);

const timeEntries = [
  {
    userId: 6,
    taskId: 1,
    caseId: null,
    notes: "Reviewed financial disclosure docs",
    startTime: ms(2, 11, 30),
    endTime: ms(2, 9, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: null,
    caseId: 1,
    notes: "Follow-up analysis",
    startTime: ms(1, 15, 45),
    endTime: ms(1, 14, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: null,
    caseId: 2,
    notes: "Draft motion research",
    startTime: ms(3, 12, 0),
    endTime: ms(3, 10, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 3,
    caseId: null,
    notes: "Prepared interview questions",
    startTime: ms(5, 10, 15),
    endTime: ms(5, 9, 30),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 4,
    caseId: null,
    notes: "Call with insurance adjuster",
    startTime: ms(1, 11, 50),
    endTime: ms(1, 11, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: null,
    caseId: 5,
    notes: "Merger agreement outline",
    startTime: ms(4, 16, 20),
    endTime: ms(4, 13, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 6,
    caseId: null,
    notes: "Zoning precedent research",
    startTime: ms(2, 9, 30),
    endTime: ms(2, 8, 0),
    isRunning: false,
  },
  {
    userId: 6,
    caseId: 1,
    notes: "Client call - Smith divorce",
    startTime: ms(0, 10, 45),
    endTime: ms(0, 10, 0),
    isRunning: false,
  },
  {
    userId: 6,
    caseId: 2,
    notes: "Site visit - downtown development",
    startTime: ms(6, 16, 0),
    endTime: ms(6, 14, 0),
    isRunning: false,
  },
  {
    userId: 6,
    caseId: 3,
    notes: "Custody evaluation prep",
    startTime: ms(4, 11, 0),
    endTime: ms(4, 9, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 1,
    caseId: null,
    notes: "Document review",
    startTime: ms(7, 10, 30),
    endTime: ms(7, 9, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 4,
    caseId: null,
    notes: "Citation checking",
    startTime: ms(8, 16, 45),
    endTime: ms(8, 15, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 4,
    caseId: null,
    notes: "Settlement counter draft",
    startTime: ms(2, 15, 30),
    endTime: ms(2, 14, 0),
    isRunning: false,
  },
  {
    userId: 6,
    caseId: 5,
    notes: "Due diligence review",
    startTime: ms(10, 13, 0),
    endTime: ms(10, 11, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 5,
    caseId: null,
    notes: "Merger terms draft",
    startTime: ms(9, 12, 15),
    endTime: ms(9, 10, 0),
    isRunning: false,
  },
  {
    userId: 6,
    notes: "Admin and billing",
    startTime: ms(0, 9, 0),
    endTime: ms(0, 8, 30),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 3,
    caseId: null,
    notes: "Teacher interview notes",
    startTime: ms(1, 14, 20),
    endTime: ms(1, 13, 0),
    isRunning: false,
  },
  {
    userId: 6,
    caseId: 4,
    notes: "Medical records review",
    startTime: ms(3, 10, 45),
    endTime: ms(3, 9, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: null,
    caseId: 2,
    notes: "Finalize research memo",
    startTime: ms(0, 15, 30),
    endTime: ms(0, 14, 0),
    isRunning: false,
  },
  {
    userId: 6,
    taskId: 1,
    caseId: null,
    notes: "Valuation summary",
    startTime: ms(11, 11, 40),
    endTime: ms(11, 10, 0),
    isRunning: false,
  },
];

const created = await TimeEntry.bulkCreate(timeEntries);
console.log(`Seeded ${created.length} time entries (userId 6).`);
await db.close();
